# Name of your application. Used to uniquely configure containers.
service: csa-admin

# Name of the container image.
image: thibaudgg/csa-admin

# Deploy to these servers.
servers:
  web:
    - isle.thibaud.gg
  job:
    hosts:
      - isle.thibaud.gg
    cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  forward_headers: true

  hosts:
    # Static hosts
    - cdn.csa-admin.org
    - mc.csa-admin.org
    - connect.csa-admin.org
    - app.csa-admin.org
    - app.acp-admin.ch

    # Tenant hosts
    <%
      tenant = YAML.load_file("#{Dir.pwd}/config/tenant.yml", aliases: true)
      tenant["production"].flat_map { |name, config|
        [ config["admin_host"], config["members_host"] ]
      }.compact.each do |host|
    %>
    - <%= host %>
    <% end %>

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: thibaudgg

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    APP_DOMAIN: csa-admin.org
    ALLOWED_COUNTRY_CODES: CH,FR,DE,IT,LI,NL
    ASSET_HOST: https://cdn.csa-admin.org
    ULTRA_ADMIN_EMAIL: info@csa-admin.org
    ULTRA_ADMIN_NAME: Thibaud
    ULTRA_ADMIN_LANGUAGE: fr
    MAINTENANCE_MODE: OFF
    WEB_CONCURRENCY: 2
    JOB_CONCURRENCY: 1

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f -n 100

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "/storage/csa-admin:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: arm64
