name: CI

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_ENV: ci
  AUBE_STORE_DIR: ~/.local/share/mise/aube-store
  BUNDLE_FROZEN: true

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Bootstrap
        uses: jdx/mise-action@v4
        with:
          bootstrap: true
          cache_key: "{{default}}-${{ hashFiles('Gemfile.lock', 'aube-lock.yaml') }}"

      - name: Locales
        run: bin/locales check

      - name: Herb format
        run: bin/herb format . --check

      - name: Oxfmt
        run: bin/oxfmt --check

      - name: RuboCop
        run: bin/rubocop --parallel --format simple

      - name: Oxlint
        run: bin/oxlint app/javascript

      - name: Stylelint
        run: >
          bin/stylelint
          app/assets/stylesheets/**/*.css

      - name: Herb lint
        run: bin/herb lint . --github

      - name: Actionlint
        run: bin/actionlint

      - name: Solid Queue
        run: bin/jobs check

      - name: Check Migration Indexes
        uses: speedshop/ids_must_be_indexed@v1

  scan:
    name: Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Bootstrap
        uses: jdx/mise-action@v4
        with:
          bootstrap: true
          cache_key: "{{default}}-${{ hashFiles('Gemfile.lock', 'aube-lock.yaml') }}"

      - name: Bundler audit
        run: bin/bundler-audit check --update

      - name: Importmap
        run: bin/importmap audit

      - name: Brakeman
        run: bin/brakeman -f sarif -o results.sarif

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif

  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Bootstrap
        uses: jdx/mise-action@v4
        with:
          bootstrap: true
          cache_key: "{{default}}-${{ hashFiles('Gemfile.lock', 'aube-lock.yaml') }}"

      - name: Set timezone
        run: echo "TZ=Europe/Zurich" >> "$GITHUB_ENV"

      - name: Prepare database
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bin/rails db:prepare

      - name: Rails
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bin/rails test:all

      - name: Seeds
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bin/rails db:seed:replant
