name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libvips

      - name: Install Ruby and run Bundler install with cache
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Node.js and run npm install
        uses: actions/setup-node@v4
      - run: npm ci

      - name: Run lint:check
        run: bin/rails lint:check

      - name: Check Migration Indexes
        uses: speedshop/ids_must_be_indexed@v1.2.1
