name: Security

on:
  schedule:
    - cron: "00 8 * * 5"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  MISE_ENV: ci
  AUBE_STORE_DIR: ~/.local/share/mise/aube-store
  BUNDLE_FROZEN: true

jobs:
  brakeman-scan:
    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Bootstrap
        uses: jdx/mise-action@v4
        with:
          bootstrap: true
          cache_key: "{{default}}-${{ hashFiles('Gemfile.lock', 'aube-lock.yaml') }}"

      - name: Brakeman Scan
        run: bin/brakeman -f sarif -o results.sarif

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif

  dependency-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Bootstrap
        uses: jdx/mise-action@v4
        with:
          bootstrap: true
          cache_key: "{{default}}-${{ hashFiles('Gemfile.lock', 'aube-lock.yaml') }}"

      - name: Bundle Audit
        run: bin/bundler-audit check --update

      - name: Importmap Audit
        run: bin/importmap audit
